// Code generated by mockery v2.14.1. DO NOT EDIT.

package main

import (
	context "context"
	sync "sync"

	mock "github.com/stretchr/testify/mock"
)

// MockConnectorInterface is an autogenerated mock type for the ConnectorInterface type
type MockConnectorInterface struct {
	mock.Mock
}

// execute provides a mock function with given fields: ctx, wg
func (_m *MockConnectorInterface) execute(ctx context.Context, wg *sync.WaitGroup) {
	_m.Called(ctx, wg)
}

type mockConstructorTestingTNewMockConnectorInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConnectorInterface creates a new instance of MockConnectorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConnectorInterface(t mockConstructorTestingTNewMockConnectorInterface) *MockConnectorInterface {
	mock := &MockConnectorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
